# Generated by Django 4.2.9 on 2024-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beheerder', '0002_delete_beheerders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onderzoek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('omschrijving', models.TextField()),
            ],
        ),
    ]
