# Generated by Django 4.2.9 on 2024-03-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beheerder', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Onderzoek',
        ),
    ]
