# Generated by Django 4.2.9 on 2024-03-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Beperkingen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.TextField()),
                ('soort', models.TextField()),
            ],
            options={
                'db_table': 'Beperkingen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BeperkingenErvaringsdeskundigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beperking_id', models.IntegerField()),
                ('ervaringsdeskundigen_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Beperkingen_ervaringsdeskundigen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deelnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'Deelnames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Onderzoeken',
            fields=[
                ('onderzoeks_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('titel', models.TextField()),
                ('omschrijving', models.TextField()),
                ('datum_vanaf', models.DateTimeField()),
                ('datum_tot', models.DateTimeField()),
                ('soort_onderzoek', models.IntegerField()),
                ('locatie', models.TextField(blank=True, null=True)),
                ('met_beloning', models.IntegerField()),
                ('beloning', models.TextField(blank=True, null=True)),
                ('doelgroep_leeftijd_van', models.IntegerField()),
                ('doelgroep_leeftijd_tot', models.IntegerField()),
                ('contact_opgenomen', models.IntegerField()),
                ('opmerkingen_beheerder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Onderzoeken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organisaties',
            fields=[
                ('organisatie_id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.TextField(blank=True, null=True)),
                ('kvk', models.TextField(blank=True, db_column='KVK', null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('beschrijving', models.TextField(blank=True, null=True)),
                ('contact_persoon', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('telefoonnummer', models.IntegerField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Organisaties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Toezichthouders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ervaringsdeskundige', models.IntegerField(blank=True, null=True)),
                ('voornaam_1', models.TextField()),
                ('achternaam_1', models.TextField()),
                ('telefoonnummer_1', models.TextField()),
                ('voornaam_2', models.TextField(blank=True, null=True)),
                ('achternaam_2', models.TextField(blank=True, null=True)),
                ('telefoonnummer_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Toezichthouders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOnderzoek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonisch', models.BooleanField(blank=True, null=True)),
                ('internet', models.BooleanField(blank=True, null=True)),
                ('locatie', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Type_onderzoek',
                'managed': False,
            },
        ),
    ]
